data_config:
    input_dir: ${SCRATCH}/heptrkx/data/hitgraphs_med_002
    name: hitgraphs
    n_train: 8192
    n_valid: 1024
    batch_size: 1
    n_workers: 4

experiment_config:
    name: gnn
    output_dir: ${SCRATCH}/heptrkx/results/gnnsegclf_med_000
    real_weight: 2.5   # 0.5 / 0.2
    fake_weight: 0.625 # 0.5 / 0.8

model_config:
    model_type: 'gnn_segment_classifier'
    input_dim: 3
    hidden_dim: 64
    n_iters: 4
    loss_func: 'binary_cross_entropy'
    optimizer: 'Adam'
    learning_rate: 0.001

train_config:
    n_epochs: 16
