data_config:
    input_dir: /global/cscratch1/sd/sfarrell/heptrkx/data/hitgraphs_001
    name: hitgraphs
    n_train: 1024
    n_valid: 1024
    batch_size: 1

experiment_config:
    name: gnn
    output_dir: /global/cscratch1/sd/sfarrell/heptrkx/results/gnnsegclf_000

model_config:
    model_type: 'gnn_segment_classifier'
    input_dim: 3
    hidden_dim: 16
    n_iters: 4
    loss_func: 'BCELoss'
    optimizer: 'Adam'
    learning_rate: 0.001

train_config:
    n_epochs: 16
